### ISSUE TITLE
Twitch username change doesn't carry over Cookies

### ISSUE THREAD

**Issue by Elbod** [Citillara/CitiBot#25]
Currently, the cookies gathered don't properly carry over if you change your name on Twitch, Example is Laxo001 12.622, all the cookies he gathers now don't increase to that.

**Comment by Citillara** [comment]
I need old name and new name

**Comment by Citillara** [comment]
I manually updated laxo001 to laxoc

Pretty annoying will have to see how i'll handle that

**Comment by Citillara** [comment]
From : 
https://help.twitch.tv/customer/portal/articles/1015624-username-rename-and-recycling-policies

> Your old username will not be recycled. Except in special circumstances, your username will not be made available again to anyone else.

In case of username change : 
If NewName Exists AND NewName Doesnt have Twitch ID
Then
Delete NewName
Update OldName to NewName
Else
Raise warning in log
EndIf

**Comment by Citillara** [comment]
Fixed
