### ISSUE TITLE
!command

### ISSUE THREAD

**Issue by Onynekyu** [Citillara/CitiBot#5]
here's another idea.

!command which gives a list a command

!leaderboard or rank. There is a link about the table, but i can't find it again :/

PS: how do i label it as "business idea" ?

**Comment by Citillara** [comment]
Technically it's implemented. !help or !commands (no singular though) and the help list is not up to date

Going to refractor the code to move the help to the website. There's too many commands and aliases

**Comment by Onynekyu** [comment]
ho my bad, and thanks :)

**Comment by Citillara** [comment]
https://github.com/Citillara/CitiBot/wiki

**Comment by Citillara** [comment]
https://github.com/Citillara/CitiBot/wiki
